name: coverage

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Generate coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests
        run: |
          cargo llvm-cov \
            --no-fail-fast \
            --workspace \
            --lib \
            --lcov \
            --output-path lcov.info \
            --ignore-filename-regex '.*(client|macros|example|pocket-ic-tests).*' \
            --exclude "ic-dbms-client" \
            --exclude "ic-dbms-macros" \
            --exclude "pocket-ic-tests" \
            --exclude "pocket-ic-tests-macro" \
            --exclude "example" \
            --exclude-from-report "ic-dbms-client" \
            --exclude-from-report "ic-dbms-macros" \
            --exclude-from-report "pocket-ic-tests" \
            --exclude-from-report "pocket-ic-tests-macro" \
            --exclude-from-report "example"
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: lcov.info
          # currently we only run one coverage report per build
          parallel: false
